dist: xenial
sudo: required

language: cpp
compiler: clang

cache:
  apt: true
  directories:
    - $HOME/deps

before_install:
  - source ./scripts/travis/defaults.sh

install:
  - DEP_DIR="$HOME/deps"
  - source ./scripts/travis/install-deps.sh
  - export CLANG_DIR

before_script:
  - ./scripts/travis/configure.sh

script:
  - ./scripts/travis/build.sh
  - ./scripts/travis/test.sh

email:
  on_success: change
  on_failure: always
