dist: xenial
sudo: required

language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - george-edison55/cmake-3.x
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - clang-3.8
            - libboost-dev
            - cmake
            - libstdc++6
      env:
        CC=clang-3.8
        CXX=clang++-3.8

cache:
  apt: true
  directories:
    - $HOME/deps

before_install:
  - source ./scripts/travis/defaults.sh

install:
  - export CC=clang-3.8
  - export CXX=clang++-3.8
  - DEP_DIR="$HOME/deps"
  - source ./scripts/travis/install-deps.sh
  - export PATH
  - export CLANG_DIR
  - export CLANG_BIN
  - export CLANGXX_BIN

before_script:
  - ./scripts/travis/configure.sh

script:
  - ./scripts/travis/build.sh
  - ./scripts/travis/test.sh

email:
  on_success: change
  on_failure: always
